"""
    Lets Chat

    Simple Api created to communicate between users  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.messages_api import MessagesApi  # noqa: E501


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_name_sender_get(self):
        """Test case for get_get_name_sender_get

        Receive messages  # noqa: E501
        """
        pass

    def test_get_new_get_new_name_sender_get(self):
        """Test case for get_new_get_new_name_sender_get

        Get number and content of new messages  # noqa: E501
        """
        pass

    def test_marked_as_read_marked_as_read_name_sender_put(self):
        """Test case for marked_as_read_marked_as_read_name_sender_put

        Mark as read  # noqa: E501
        """
        pass

    def test_post_all_send_all_post(self):
        """Test case for post_all_send_all_post

        Send message to All  # noqa: E501
        """
        pass

    def test_post_send_sender_username_receiver_username_message_post(self):
        """Test case for post_send_sender_username_receiver_username_message_post

        Send message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
