"""
    Lets Chat

    Simple Api created to communicate between users  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_active_users_active_users_get(self):
        """Test case for active_users_active_users_get

        Print active users  # noqa: E501
        """
        pass

    def test_logout_logout_post(self):
        """Test case for logout_logout_post

        LogOut  # noqa: E501
        """
        pass

    def test_put_login_post(self):
        """Test case for put_login_post

        Enter your login  # noqa: E501
        """
        pass

    def test_put_register_post(self):
        """Test case for put_register_post

        Register  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
